find_package(Python3 3.9 REQUIRED COMPONENTS Interpreter)
if(BUILD_GENIE)
    add_executable(make-gst-fixture make_gst_fixture.cpp)
    target_link_libraries(make-gst-fixture PRIVATE ROOT::Tree ROOT::RIO)
endif()
if(BUILD_UNIFORM)
    add_test(NAME uniform-integration COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/integration.py uniform $<TARGET_FILE:clas12-uniform>)
endif()
if(BUILD_GENIE)
    add_test(NAME genie-integration COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/integration.py genie $<TARGET_FILE:clas12-genie-to-lund> $<TARGET_FILE:make-gst-fixture>)
endif()
if(BUILD_UNIFORM)
    add_test(NAME simulation-integration COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/simulation.py $<TARGET_FILE:clas12-uniform> ${PROJECT_SOURCE_DIR})
endif()
