# Supply --input and --output at runtime. GENIE is the default physical adapter.
event-generator = genie
event-generator-version = unknown
tune = unknown
q2-cut = Q2_0_40
gemc-version = 5.14
beam-energy = 5.98636
rgm-target = Ar40
events = 10000000
vertex-seed = 12345
prefix = GENIE_Ar40_5986MeV
