channel = en
beam-energy = 5.98636
target = Ar
A = 40
Z = 18
events = 1000
seed = 67890
vertex-seed = 12345
prefix = Uniform_sample_en_5986MeV
nucleon-theta-min = 5
nucleon-theta-max = 35
nucleon-momentum = fixed
nucleon-p = 1
trigger-theta = 25
trigger-phi-offset = 5
