channel = ep
beam-energy = 5.98636
rgm-target = Ar40
events = 10000
prefix = Uniform_sample_ep_5986MeV
nucleon-momentum = sampled
nucleon-angle = auto
nucleon-p-min = 0.3
nucleon-p-max = auto
lund-format = legacy
