if(BUILD_UNIFORM)
    add_executable(clas12-uniform uniform_main.cpp)
    target_link_libraries(clas12-uniform PRIVATE UniformGeneration)
    install(TARGETS clas12-uniform RUNTIME DESTINATION bin)
endif()
if(BUILD_GENIE)
    add_executable(clas12-genie-to-lund genie_to_lund_main.cpp)
    target_link_libraries(clas12-genie-to-lund PRIVATE GenieConversion)
    install(TARGETS clas12-genie-to-lund RUNTIME DESTINATION bin)
endif()
